### ISSUE TITLE
adm-dados | Meta atributos para políticos e posições políticas

### ISSUE THREAD

**Issue by ghost** [ops-org/projeto-novo-eleitor#12]
Os meta-atributos são definidos a partir de códigos formatados a fim de se obter sua relação hierárquica a partir de seu próprio número, tal codificação se dará pela formatação de seu próprio número em 3 partes, divididas em: 
**[2 dígitos para grupo primário] + [2 dígitos para sub-grupo]+ [3 dígitos para o atributo]**
os registros para cada atributo para um respectivo político serão armazenados nas tabelas **_meta_10**, onde meta_10 são todos os atributos do grupo 10.

Inicialmente teremos os seguintes grupos primários:

**Grupos Primários para armazenamento de informações politicas**
- [ ] 10-Cidadão Política: Informações Gerais
- [ ] 11-Cadastro Formas de Contato, conexões e redes sociais
- [ ] 12-Cidadão: Patrimônio / Bens
- [ ] 50-Critérios de avaliação dos políticos

## Lista completa de MetaAtributos
- [ ] 1000000-Cidadão Política: Informações Gerais
- [x] 1000001-----Sexo
- [x] 1000002-----Cor da Pele
- [x] 1000003-----Data de Nacimento
- [x] 1000004-----Data de Falecimento
- [x] 1000005-----Nacionalidade
- [x] 1000006-----Estado Civil
- [x] 1000007-----Naturalidade
- [x] 1000008-----Ocupação
- [x] 1000009-----Escolaridade
- [x] 1000010-----Gentílico
- [x] 1000011-----Partido
- [x] 1000012-----Número Urna
- [x] 1000013-----Ano Eleição
- [x] 1000014-----Nome Político
- [x] 1000015-----Nome Civil
- [x] 1000016-----CPF
- [x] 1000017-----Cargo Público Atual
- [x] 1000018-----Político desde
- [ ] 1001000---Fotos
- [ ] 1001001-----Foto Social Facebook
- [ ] 1001002-----Foto Social Twitter
- [ ] 1100000-Cadastro Formas de Contato, conexões e redes sociais
- [ ] 1101000---Contato telefônico clássico
- [ ] 1101001-----Telefone
- [ ] 1101002-----Celular
- [ ] 1101003-----Comercial
- [ ] 1101004-----Residêncial
- [ ] 1101005-----Fax
- [ ] 1101009-----Outros
- [ ] 1103000---Mensagens Eletrônicas
- [ ] 1103001-----E-mail
- [ ] 1103002-----E-mail Assessoria
- [ ] 1103003-----E-mail Particular
- [ ] 1103010-----WhatsApp
- [ ] 1103011-----Telegram
- [ ] 1103012-----Skype
- [ ] 1103013-----Facebook Messenger
- [ ] 1104000---Endereço Comercial
- [ ] 1104001-----Rua / Logradouro
- [ ] 1104002-----Caixa Postal
- [ ] 1104003-----Sala
- [ ] 1104004-----Bairro
- [ ] 1104005-----Cidade
- [ ] 1104006-----Estado
- [ ] 1104007-----CEP
- [ ] 1104008-----País
- [ ] 1105000---Endereço Residêncial
- [ ] 1105001-----Rua / Logradouro
- [ ] 1105002-----Caixa Postal
- [ ] 1105003-----Bairro
- [ ] 1105004-----Cidade
- [ ] 1105005-----Estado
- [ ] 1105006-----CEP
- [ ] 1105007-----País
- [ ] 1109000---Endereço Outros
- [ ] 1109001-----Rua / Logradouro
- [ ] 1109002-----Caixa Postal
- [ ] 1109003-----Bairro
- [ ] 1109004-----Cidade
- [ ] 1109005-----Estado
- [ ] 1109006-----CEP
- [ ] 1109007-----País
- [ ] 1110000---Redes Sociais
- [ ] 1110001-----Facebook
- [ ] 1110003-----Twitter
- [ ] 1110004-----Google+
- [ ] 1110005-----Instagram
- [ ] 1110006-----LinkedIn
- [ ] 1110007-----YouTube
- [ ] 1110008-----Colnect
- [ ] 1110009-----CouchSurfing
- [ ] 1110010-----Cyworld
- [ ] 1110011-----Ello
- [ ] 1110013-----Filmow
- [ ] 1110014-----Flickr
- [x] 1200000-Cidadão: Patrimônio / Bens
- [x] 1200001-----Prédio residencial
- [x] 1200002-----Prédio comercial
- [x] 1200003-----Galpão
- [x] 1200011-----Apartamento
- [x] 1200012-----Casa
- [x] 1200013-----Terreno
- [x] 1200014-----Terra nua
- [x] 1200015-----Sala ou conjunto
- [x] 1200016-----Construção
- [x] 1200017-----Benfeitorias
- [x] 1200018-----Loja
- [x] 1200019-----Outros bens imóveis
- [x] 1200021-----Veículo automotor terrestre: caminhão, automóvel, moto, etc.
- [x] 1200022-----Aeronave
- [x] 1200023-----Embarcação
- [x] 1200024-----Bem relacionado com o exercício da atividade autônoma
- [x] 1200025-----Jóia, quadro, objeto de arte, de coleção, antiguidade, etc.
- [x] 1200026-----Linha telefônica
- [x] 1200029-----Outros bens móveis
- [x] 1200031-----Ações (inclusive as provenientes de linha telefônica)
- [x] 1200032-----Quotas ou quinhões de capital
- [x] 1200039-----Outras participações societárias
- [x] 1200041-----Caderneta de poupança
- [x] 1200045-----Aplicação de renda fixa (CDB, RDB e outros)
- [x] 1200046-----Ouro, ativo financeiro
- [x] 1200047-----Mercado futuros, de opções e a termo
- [x] 1200049-----Outras aplicações e Investimentos
- [x] 1200051-----Crédito decorrente de empréstimo
- [x] 1200052-----Crédito decorrente de alienação
- [x] 1200053-----Plano PAIT e caderneta de pecúlio
- [x] 1200054-----Poupança para construção ou aquisição de bem imóvel
- [x] 1200059-----Outros créditos e poupança vinculados
- [x] 1200061-----Depósito bancário em conta corrente no País
- [x] 1200062-----Depósito bancário em conta corrente no exterior
- [x] 1200063-----Dinheiro em espécie - moeda nacional
- [x] 1200064-----Dinheiro em espécie - moeda estrangeira
- [x] 1200069-----Outros depósitos à vista e numerário
- [x] 1200071-----Fundo de investimento financeiro - FIF
- [x] 1200072-----Fundo de aplicação em quotas de fundos de investimento
- [x] 1200073-----Fundo de capitalização
- [x] 1200074-----Fundo de ações, inclusive Carteira Livre e Fundo de Investimento no exterior
- [x] 1200079-----Outros fundos
- [x] 1200091-----Licença e concessões especiais
- [x] 1200092-----Título de clube e assemelhado
- [x] 1200093-----Direito de autor, de inventor e patente
- [x] 1200094-----Direito de lavra e assemelhado
- [x] 1200095-----Consórcio não contemplado
- [x] 1200096-----Leasing
- [x] 1200097-----VGBL - Vida Gerador de Benefício Livre
- [x] 1200099-----Outros bens e direitos
- [ ] 5000000-Critérios de avaliação dos políticos
- [ ] 5001000---Infidelidade eleitoral ao voto
- [ ] 5001001-----Renúncia de cargo para almejar um melhor
- [ ] 5001003-----Infidelidade ao voto
- [ ] 5001004-----Votos contrários ao consenso popular
- [ ] 5002000---Problemas com a Justiça
- [x] 5002001-----Processo judicial STF
- [ ] 5002003-----Processo judicial municipal
- [ ] 5002004-----Processo judicial estadual
- [ ] 5002005-----Processo judicial federal
- [ ] 5003000---Imoralidade Financeira
- [ ] 5003001-----Imoralidade Financeira
- [ ] 5004000---Familiares em cargos públicos

A faixa de grupo do 01 ao 09 estará reservada aos processos internos do sistema.
E para o uso padrão de armazenamento de dados o grupo inicial será a partir do GRUPO 10 (Cidadão Política: Informações Gerais)

**Comment by ghost** [comment]
Demanda fechada por mudança de escopo
